# Generated by Django 3.2.8 on 2021-10-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id_question', models.IntegerField(primary_key=True, serialize=False)),
                ('text_question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_title', models.TextField()),
                ('id_set', models.ManyToManyField(to='TestingService.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('flag_choice', models.BooleanField()),
                ('question_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestingService.questions')),
            ],
        ),
    ]
